apiVersion: v1
kind: Secret
metadata:
  name: magento-secrets
  namespace: magento
  labels:
    app: magento
    environment: dev
type: Opaque
stringData:
  # MySQL Credentials
  DB_USER: "magento"
  DB_PASSWORD: "icube-test"
  DB_ROOT_PASSWORD: "icube-test"

  # OpenSearch Initial Admin Password (must be at least 8 chars, 1 uppercase, 1 lowercase, 1 digit, 1 special char)
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "X7$kL9#mP2@vQ5!W"

  # Magento Admin User Credentials
  MAGENTO_ADMIN_USER: "admin"
  MAGENTO_ADMIN_PASSWORD: "icube-test"
  MAGENTO_ADMIN_EMAIL: "admin@icube.test"
  MAGENTO_ADMIN_FIRSTNAME: "Admin"
  MAGENTO_ADMIN_LASTNAME: "iCube"
