---
- name: Get dynamic Minikube cluster IP
  ansible.builtin.command: minikube ip
  register: get_minikube_ip
  changed_when: false
  failed_when: false

- name: Set dynamic minikube_ip fact if Minikube is running
  ansible.builtin.set_fact:
    minikube_ip: "{{ get_minikube_ip.stdout }}"
  when: get_minikube_ip.rc == 0 and get_minikube_ip.stdout != ""

- name: Wait for Ingress Controller service to be created
  ansible.builtin.command: kubectl get svc -n ingress-nginx ingress-nginx-controller
  register: wait_ingress_svc
  until: wait_ingress_svc.rc == 0
  retries: 12
  delay: 5
  changed_when: false
  failed_when: false

- name: Get dynamic Ingress Controller NodePort HTTP
  ansible.builtin.command: kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}'
  register: get_ingress_nodeport
  changed_when: false
  failed_when: false

- name: Set dynamic nodeport_http fact if Ingress service exists
  ansible.builtin.set_fact:
    nodeport_http: "{{ get_ingress_nodeport.stdout }}"
  when: get_ingress_nodeport.rc == 0 and get_ingress_nodeport.stdout != ""

- name: Ensure Nginx reverse proxy configuration directory exists
  ansible.builtin.file:
    path: "{{ nginx_proxy_dir }}/conf.d"
    state: directory
    mode: '0755'
    recurse: true

- name: Template out Docker Compose configuration for Nginx reverse proxy
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ nginx_proxy_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart Nginx Docker Container

- name: Template out Nginx Magento reverse proxy configuration
  ansible.builtin.template:
    src: nginx-magento.conf.j2
    dest: "{{ nginx_proxy_dir }}/conf.d/default.conf"
    mode: '0644'
  notify: Reload Nginx Docker Container

- name: Ensure Nginx reverse proxy Docker container is started
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ nginx_proxy_dir }}"
  register: compose_up
  changed_when: "'Started' in compose_up.stdout or 'Created' in compose_up.stdout"
